
export default {
    GET: 'POST__GET',
    GET_ORDER: 'POST__GET_ORDER',
    
    GET_OLD: 'POST__GET_OLD',
    GET_OLD_ORDER: 'POST__GET_OLD_ORDER',

    INSERT: 'POST__INSERT',
    INSERT_ORDER: 'POST__INSERT_ORDER',

    LIKE: 'POST__LIKE',
    DISLIKE: 'POST__DISLIKE',
    SET_REACTIONS: 'POST__SET_REACTIONS',
    
    INCREMENT_NEW_POST: 'NEW_POST__INCREMENT',
    RESET_NEWS_POSTS: 'NEW_POST__RESET'
}