
export default {
    GET: 'POST__GET',
    GET_ORDER: 'POST__GET_ORDER',
    INSERT: 'POST__INSERT',
    INSERT_ORDER: 'POST__INSERT_ORDER',
    LIKE: 'POST__LIKE',
    DISLIKE: 'POST__DISLIKE',

    DECREMENT_NEW_POST: 'NEW_POST__DECREMENT',
    INCREMENT_NEW_POST: 'NEW_POST__INCREMENT',
    RESET_NEWS_POSTS: 'NEW_POST__RESET'
}