version: '3.3'

services:
    ruby:        
        build: . 
        command: 'rake start'
        ports: 
            - 3000:3000        
        volumes: 
            - ./:/rails_app

#docker exec -it name /bin/bash