version: '3.3'

services:
    ruby:
        image: ruby:3.0.2
        command: sh -c "
            cd container &&        
            apt-get update &&
            apt install -y nodejs &&     
            apt install -y npm &&
            npm install --global -y yarn &&             
            bundle update &&            
            rails webpacker:install &&
            rake start"
        # entrypoint: sh -c "rake start"
        ports: 
            - 3000:3000
        working_dir: /.
        volumes: 
            - ./:/container
