version: '3.3'

services:
    ruby:        
        build: .         
        command: bash -c 'bundle install && bundle update && rake start'
        stdin_open: true
        tty: true
        ports: 
            - 3000:3000        
        volumes: 
            - ./:/rails_app

#docker exec -it name /bin/bash